### ISSUE TITLE
Clean bower.json

### ISSUE THREAD

**Issue by lxbrito** [PolymerElements/neon-elements#2]
The 'main' and 'description' entries in bower.json are with improper escaped quotation marks. Also the 'main' entry is referring to a non-existent file and should be removed.

**Comment by addyosmani** [comment]
Are you sure the quotation marks are improperly escaped? I just ran the bower.json through a validator and it appears to be validating fine, but will double check.

@notwaldorf I think pretty much all of our meta-packages (neon-_, paper-_ etc) have a placeholder for the `main` entry that doesn't exist. We were thinking about creating an import-everything import for them but that didn't get done before I/O. Any thoughts on whether we should create something vs drop this field?

**Comment by lxbrito** [comment]
They are correctly escaped, but improperly escaped. I mean, they doesn't need to be escaped. All the problem is not with Bower, but with Rails integration. When compiling the assets, it does evaluate the 'main' prop, and breaks. In that particular case it search for /root_path/components/"neon-elements.html", with the quotation included as filename. However, even the unescaped version would break as this file does not exists.

The 0.5 core and paper elements have the referenced html with all the imports. As @addyosmani said at the same discussion at paper-elements, Bower will throw a quiet exception if the field is missing, so I think it's healthier to have the missing file instead. If you wish, I can make a pull-request for each of the -elements projects.

[Off-topic] Does the Polymer project have a dev-mailing list? Just address some questions that doesn't belongs to here.

**Comment by notwaldorf** [comment]
@addyosmani @lxbrito  I think I've actually fixed the weird escaped quotes on master, but didn't push a release because it seemed like it was a purely cosmetic change. I'll fix the `main.html` issue today, and push a new release.
